Update translation_es.xml
Courseplay/Courseplay_FS25 pull request #140
Opened 2024-12-27 00:16 UTC by santixV8

I reviewed and made the changes based on the English translation file.
Please let me know if you find any further differences.

[CP Spanish Translation.zip](https://github.com/user-attachments/files/18256290/CP.Spanish.Translation.zip)

2024-12-27 09:49 UTC, Tensuko commented
@KCHARRO

2024-12-27 15:08 UTC, KCHARRO requested changes
Linea 400 - 401: Aquí siempre tuve dudas, pues no tenía muy claro qué hacía esto...

Podría se así en la descripción:
Permite activar el Mouse al presionar el botón derecho del mouse fuera de los vehículos, para interactuar con la Ventana de Textos Informativos.

Línea 609: "- Dirección del cabecero" debería ser:

Español Internacional: "Dirección de Cabeceras" 
Español Latinoamericano: "Dirección de Promontorios"

Línea 662: al final, debería ser:

... configuración global del curso. (no "juego de campo") ya que esto pertenece al Generador de Cursos.

Líneas 666, 667, 668: headlands

En algunos países de latinoamérica se traduce como Promintorios, en la mayoría de países de habla hispana como Cabeceras. 

Utilicé cabeceras porque este es "Español Internacional"

En el "Español Latinoamericano" si puedes dejarlo como "Promontorios"

Igual sucede con los "Viñedos" que también se conoce como "Vides"(aquí usar cualquiera de los dos es válido en cualquie país)
Siempre comprueba con varios traductores diferentes, pues la mayoría traduce literalmente y a veces hay que rectificarlo manualmente...

Líneas: 669, 670, 671, 672: Debería quedarse com estaba:

por ejemplo "Generador de Cursos: Centro"

porque son ajustes que pertenecen a diferentes partes de un mismo Curso que se generará...


Línea 638: -Lands

Siempre he tenido dudas con la traducción de "Lands" del "Generador de Cursos" en "Centro del Campo"

Se refiere a la forma de trabajar el centro del campo.

En E.E.U.U se llama "Lands" se traduce como "Tierras" 
Aquí en Cuba le decimos por ejemplo "Arar en Embergas"
En España no sé cómo le llaman a ese modo de trabajo(por eso mantuve la traducción literal que es "Tierras")

¿Puedes investigar cómo los agricultores le llaman en tu país?...

--------------------------------------------------------------------------

Line 400 - 401: I always had doubts here, because I wasn't very clear about what this was doing...

It could be like this in the description:
Permite activar el Mouse al presionar el botón derecho del mouse fuera de los vehículos, para interactuar con la Ventana de Textos Informativos.

Line 609: "- Dirección del cabecero" should be:

International Spanish: "Dirección de Cabeceras" 
Latin American Spanish: "Dirección de Promontorios"

Line 662: At the end, it should be:

... configuración global del curso. (not "juego de campo") as this belongs to the Course Generator.

Lines 666, 667, 668: headlands

In some Latin American countries it is translated as "Promontorios", in most Spanish-speaking countries as "Cabeceras". 

I used "Cabeceras" because this is "Spanish International"

In "Latin American Spanish" you can leave it as "Promontorios"

The same happens with "Viñedos" which are also known as "Vides" (here using either of the two is valid in any country)
Always check with several different translators, since most translate literally and sometimes you have to correct it manually...

Lines: 669, 670, 671, 672: Should stay as it was:

for example "Generador de Cursos: Centro"

because they are settings that belong to different parts of the same Course that will be generated...

Lline 638: -Lands

I have always had doubts with the translation of "Lands" from the "Generador de Cursos" in  "Centro del Campo"

It refers to the way of working the center of the field.

In the US is "Lands" it translates as "Tierras"
Here in Cuba we say, for example, "Arar en Embergas"
In Spain I don't know what they call that way of working (that's why I kept the literal translation, which is "Tierras")

Can you research what farmers call it in your country?...

2024-12-27 17:00 UTC, santixV8 commented
Gracias por tus comentarios, estaba casi seguro que alguna cosa se me podía pasar por alto.
De todas formas, quería comentarte que la palabra "promontorio" no me suena para nada, busqué en Google y lo más parecido es montículo de tierra o peñón, cito Wikipedia: "Un promontorio es una prominente masa de tierra que sobresale de las tierras más bajas en que descansa o de un cuerpo de agua1 (cuando es este el caso, se habla de península o cabo)" y no se condice con la parte del campo a la que se refiere. Yo soy de Uruguay y sinceramente nunca escuché esa palabra aquí ni en algún país vecino, por lo que entiendo que al dejar la palabra "cabecera" va a ser más adecuado ya que no genera una diferencia tan significativa y a esta altura todos los que usamos este mod y el juego entendemos a qué se refiere.
La idea de subir la traducción a español LATAM era más que nada porque ahora el juego incorpora esa opción de idioma para elegir, y por defecto Courseplay no lo detecta y te muestra toda la interfaz en inglés, más allá de que hay un archivo de traducción en español aunque a este no lo reconoce al estar configurado en LATAM. 
¿A que voy con esto? Que en realidad (supongo) en LATAM estamos acostumbrados a usar el juego con las palabras de la traducción de español España, por lo que asumí que no era necesario modificar tanto el archivo nuevo translate_ea porque ya venimos usandolo como si estuviéramos en España. Ejemplo: aquí en Uruguay y en Argentina a las pacas le decimos rollos o fardos, pero en España fardo es una cosa totalmente diferente a la agricultura. Por ese motivo consideré que no era una diferencia tan grande como para tener que estar editando los dos archivos por separado.
Dime qué piensas acerca de esto, con respecto al resto de cambios que sugeriste, los voy a hacer apenas llegue a casa y tenga acceso al pc.
Saludos :)

Thanks for your comments, I was almost sure that I might have missed something.
Anyway, I wanted to tell you that the word "promontory" doesn't sound familiar to me at all, I searched on Google and the closest thing is mound of earth or rock, I quote Wikipedia: "A promontory is a prominent mass of land that protrudes from the lower lands on which it rests or from a body of water1 (when this is the case, we speak of a peninsula or cape)" and it doesn't match the part of the land to which it refers. I am from Uruguay and honestly I have never heard that word here or in any neighboring country, so I understand that leaving the word "header" will be more appropriate since it does not generate such a significant difference and at this point all of us who use this mod and the game understand what it refers to.
 The idea of uploading the translation to Spanish LATAM was mostly because now the game includes that language option to choose from, and by default Courseplay doesn't detect it and shows you the entire interface in English, beyond the fact that there is a translation file in Spanish although it doesn't recognize it when configured in LATAM. 
What am I getting at with this? In reality (I suppose) in LATAM we are used to using the game with the words from the Spanish translation Spain, so I assumed that it wasn't necessary to modify the new translate_ea file so much because we are already using it as if we were in Spain. Example: here in Uruguay and Argentina we call the pacas rollos or fardos, but in Spain Fardos is a totally different thing from agriculture. For that reason I considered that it wasn't such a big difference as to have to be editing the two files separately. 
Tell me what you think about this, regarding the rest of the changes you suggested, I'm going to make them as soon as I get home and have access to the PC. 
Greetings :)

2024-12-27 17:58 UTC, KCHARRO commented
Estoy completamente de acuerdo, pero que sí es conveniente crear el archivo de traducción "ea", tengo un amigo aquí, que le aparece en "ingles" porque su PC tiene la región configurada en latinoamérica, yo siempre uilizo región "España" e idioma "Español Internacional" para evitar este tipo de cosas del idioma. Y ver si el juego lo reconoce así como "_ea".

Así los usuarios no deberán estar cambiando nada en el Sistema Operativo, además que el juego base lo tiene...

Y estoy de acuerdo con tu opinión, mantengamos "Cabeceras de los Campos" en ambos archivos...

I completely agree, but it is convenient to create the "ea" translation file. I have a friend here, and it appears in "English" because his PC has the region set to Latin America. I always use the "Spain" region and language. "Spanish International" to avoid this kind of language stuff. And see if the game recognizes it as "_ea".

This way, users should not be changing anything in the Operating System, plus the base game has it...

And I agree with your opinion, let's keep "Cabeceras de los Campos" in both files...
---------------------------------------------------------------------------------------------------------------------------------
He estado buscando información, sin encontrar nada útil sobre esto:
Línea 638: -Lands

Siempre he tenido dudas con la traducción de "Lands" del "Generador de Cursos" en "Centro del Campo"

Se refiere a la forma de trabajar el centro del campo.

En E.E.U.U se llama "Lands" se traduce como "Tierras"
Aquí en Cuba le decimos por ejemplo "Arar en Embergas"
En España no sé cómo le llaman a ese modo de trabajo(por eso mantuve la traducción literal que es "Tierras")

¿Puedes investigar cómo los agricultores le llaman en tu país?...


I've been searching for information, without finding anything useful about this:
Lline 638: -Lands

I have always had doubts with the translation of "Lands" from the "Course Generator" in "Center of Field"

It refers to the way of working the center of the field.

In the US is "Lands" it translates as "Tierras"
Here in Cuba we say, for example, "Arar en Embergas"
In Spain I don't know what they call that way of working (that's why I kept the literal translation, which is "Tierras")

Can you research what farmers call it in your country?...

2024-12-27 23:41 UTC, santixV8 commented
Con respecto a la línea 638: -Lands, no tengo idea como resolverlo. Entiendo que la función principal es para que la cosechadora se sitúe con el tubo de descarga apuntando hacia los bordes del campo, pero no le encuentro una traducción viable para el español. Supongo que será mejor dejarlo como tú dices con la traducción literal

2024-12-28 03:57 UTC, KCHARRO approved these changes

2024-12-28 03:58 UTC, KCHARRO commented
Everything's fine...

2024-12-28 10:48 UTC, merged

2024-12-28 10:48 UTC, Tensuko commented
Thanks both of you.