Fix Callstack when finishing a mission while in vehicle of mission
Courseplay/Courseplay_FS25 pull request #251
Opened 2024-12-31 14:11 UTC by tn4799

Fixes #215 

One thing i thought, that might should be done in a different way for this fix:
Set the node to nil in `CPUtil.destroyNode` after calling `delete`.

2025-01-02 08:45 UTC, pvaiko requested changes

2025-01-02 08:45 UTC, pvaiko commented on scripts/gui/CourseDisplay.lua
> +	if not self.rootNode then
I'd prefer something like we do elsewhere:
`if self.rootNode and entityExists(self.rootNode) then .. `

That way there is no need to do anything elsewhere.

2025-01-04 19:40 UTC, pvaiko requested changes

2025-01-04 19:40 UTC, pvaiko commented on scripts/gui/CourseDisplay.lua
> +	if self.rootNode then
and entityExists(rootNode)

2025-01-04 19:40 UTC, pvaiko commented on scripts/gui/CourseDisplay.lua
> +	self.rootNode = nil
and this isn't needed when we use entityExists()...

2025-01-05 18:21 UTC, Tensuko commented
@schwiti6190 fixed it in another PR, thank you anyway :)

2025-01-05 18:21 UTC, closed without merging